### ISSUE TITLE
Endpoint /accounts/:accountId/metadata

### ISSUE THREAD

**Issue by p4u** [vocdoni/interoperability#109]
The new endpoint `/accounts/:accountId/metadata` returns only the account metadata object.

If the account provides from archive, and does not exist on the blockchain state, it will also be returned.

On the other side, the `/accounts/:accountId` endpoint works as usual but does not return anymore the archive accounts.

`curl -s http://localhost:9090/v2/accounts/38d2bc91b89928f78cbab3e4b1949e28787ec7a3/metadata`

```json
{
  "version": "1.0",
  "name": {
    "default": "vocdoni stuff #1"
  },
  "description": {
    "default": ""
  },
  "newsFeed": {
    "default": ""
  },
  "media": {},
  "meta": {}
}
```

### Tasks

- [ ] integrated on the SDK
- [ ] updated on the UI
- [ ] updated on the Explorer
- [ ] documentation

**Comment by elboletaire** [comment]
How does this affect the UI and explorer? Given the nature of the change, wouldn't suffice by just updating the behavior in the SDK? Maybe I'm missing something here 😅

**Comment by jpaulet** [comment]
@marcvelmer should we update something in the UI or we can close this issue?
