### ISSUE TITLE
Private & Encrypted voting processes

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/interoperability#147]
As an organizer, I want the ability to determine the visibility of the voting process, either for everyone or exclusively for members of the census who have successfully authenticated.

When the new metadata is configured with 'private = true,' the voting process must be securely stored. When a voter is accessing the voting page, the login form should be the initial prompt. The displayed data should only be visible if the voters successfully authenticate; otherwise, all information remains private.

On the organization page, the voting process details should be accessible exclusively to the authenticated user with admin privileges. If the user is not an admin, a 'Private process' indicator should be displayed.

**Tasks Backend/SDK:**
- [ ] Use the existing metadata field (encrypted metadata)
- [ ] SDK: When "private=true", encrypt the info metadata (title, description, questions..)
- [ ] Prepare everything needed, in order to let the UI read the process data, and render it depending on this metadata.
- [ ] Test it

**Tasks UI:**
- [ ] Add the new option & password input in the process creation, explaining that the voters must have the password
- [ ] Store the password as admin in the localStorage
- [ ] If the URL has a #password=xyz use the password to decrypt the data
- [ ] If possible, add the password field inside the login form, as an extra input
- [ ] Add the form to introduce the password in the voting page & decrypt the data
- [ ] Store the password on localStorage for voters that already entered the password
- [ ] Test it

**Comment by jpaulet** [comment]
Splitted in 2 different issues: private voting & encrypted metadata. Closing this one.
