### ISSUE TITLE
Farcaster Frame <> Onvote

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/interoperability#156]
As Vocdoni, we want to create and launch a new integration between Vocdoni and Farcaster, allowing the users to create a poll in an external page `farcaster.vote` with one question and up to 4 options, that will generate a link that can be embedded into farcaster as a Frame, an let the people vote directly on that social network:

### **Tasks Backend:**
- [x] Finish the Airstack census creation
- [x] Image Generation
- [x] Auth

### **Tasks SDK:**
- [ ] TBD: Implement a change in the SDK to adapt the census origin & the proof... 

### **Tasks Frontend:**
**Voting Form Creation Page**
- [ ] Implement the new look & feel of the voting form page & frames look from Flooc.

**Farcaster.vote app**
- [x] Make the questions/results render properly (index problem)
- [x] Solve the problem with the images (LRU { ID => PNG_BYTES })
- [ ] Add top process creators in the lists

**CURRENT FEATURES:**
- [x] Bot
- [x] Channel Gated
- [x] Token Gated
- [x] #175
- [x] #176
- [x] #178
     - Add NFTs for reputation
- [x] #177

**Next Sprints:**
- [ ] Add Census3 token lists (different networks) integration into Farcaster.vote
- [ ] Paid Features
     - [ ] Discuss how to $$$ 
     - [ ] NFTs
     - [ ] Census3 specific tokens
     - [ ] Big census (>X k. holders)

Extra:
- [ ] Vote delegation
- [ ] Vote overwrite
- [ ] Render the onvote process on Farcaster
- [ ] _Improve a bit the UI of the explorer when someone checks their vote._
- [ ] _Move the verify vote field at the bottom, it confuses the user specially when checking from the phone_           
- [ ] _Move the tag (“none” in this case) after the sentence._
- [x] _Equilibrate the weight of the content. The title is aligned to the left, the icon of the ballot box to the center, then the next text to the left and then the next one to the center. We should redesign a bit this._
