### ISSUE TITLE
Misc Improvements

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/interoperability#167]
- [x] **[Bug]** When resuming (play) a paused process, the toast message is wrong: https://github.com/vocdoni/ui-scaffold/issues/576
- [x] **[Bug]** Vote button is enabled for a finished anonymous election: https://github.com/vocdoni/ui-components/issues/151  
- [x] **[Bug]** Stream visualization on mobile devices looks like a wrongly positioned ad: https://github.com/vocdoni/ui-scaffold/issues/564
- [x] **[Improvement]** Wallet addresses census visual improvement: https://github.com/vocdoni/ui-scaffold/issues/598
- [x] **[Improvement]** Improve token logo images loading per network: https://github.com/vocdoni/ui-scaffold/issues/583
- [x] **[Improvement]** Improve Onvote census info: https://github.com/vocdoni/ui-scaffold/issues/562
- [x] **[Improvement]** Ensure supported census strategies allow weighted census: https://github.com/vocdoni/ui-scaffold/issues/551
- [x] **[Improvement]** Upgrade the onvote faucet to be the same as app.vocdoni.io: https://github.com/vocdoni/interoperability/issues/169
- [x] **[Improvement]** End date improvement: https://github.com/vocdoni/ui-scaffold/issues/593
- [x] **[Improvement]** Share options in the voting page: https://github.com/vocdoni/interoperability/issues/148
- [x] **[Improvement]** Post PxLL issues https://github.com/vocdoni/ui-components/issues/153
- [x] **[Improvement]** Add meta-tag "app name" https://github.com/vocdoni/ui-scaffold/issues/550
- [x] **[Improvement]** Gitcoin responsive issues: https://github.com/vocdoni/ui-scaffold/issues/616
