### ISSUE TITLE
EPIC - SaaS Backend MVP v1

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/interoperability#192]
The SaaS Backend should allow to:

### **Admin Registration and Authentication**

**Admin Registration (CRUD)**

- [x] Develop API endpoint for admin registration (email, password, full name, org_id).
- [x] Create admin object schema and store in the database. Admins can administrate X orgs/suborgs.
- [x] Implement email validation service integration.
- [x] Set up email sending service

**Admin Login**
- [x] Develop API endpoint for user login.
- [x] Set up session/token management.

**Email Verification**
- [x] Develop API endpoint for email verification.
- [x] Update user status in the database upon verification.

### Organization Management
**Create Organization**
- [x] Develop API endpoint for organization creation _(name, description, type, size, email, url, social, logo, timezone, color, short url, parent_org_id, created_at, active, owner_id)_.
- [x] Create organization object schema and store in the database.
- [x] Manage the related account PK into the DB, in order that all admins can act in behalf of the org

**Manage Organization Data**
- [x] Develop API endpoint for fetching organization details.
- [x] Develop API endpoint for updating organization details.
- [x] Fetch team members of an organization

**Sub-Organization Management**
- [x] Develop API endpoints for creating, updating, and deleting sub-organizations.
- [x] Check if the plans allows to create orgs and prevent to create more than the fixed number of orgs
- [x] Create sub-organization object schema and store in the database.
- [x] Set the admin to the new sub-org

### Token Management
**Extend our API allowing to create all the TX that needs tokens with the backend and a faucetPackage**
- [x] Create Process
- [x] Play/Pause/Stop/Cancel
- [x] Change account details

**V1:**

**Password Recovery**
- [x] Develop API endpoint for password recovery requests.
- [x] Implement email service to send password recovery links.
- [x] Develop API endpoint to handle password reset.

**Invite Admins**
- [x] Develop API endpoint for inviting additional admins (by email).
- [x] Implement email service to send invitations.
- [x] Handle invitation acceptance, set the password and update the database.

**Comment by jpaulet** [comment]
Closing this epic, as all the issues are finished and we moved those 2 to specific issues to control the checks/permissions in the backend:

### Voting Process Creation
- [ ] #227
    - [ ] Develop API endpoint to handle voting process creation and store details in the database and blockchain.
    - [ ] Check if all the conditions are meet to create the process (isAdmin, max_census_size, active plan, etc.). If so, allow any admin to create the voting process without having to purchase tokens (token manager).
    - [ ] Allow adding extra-features/data into the voting process, like: custom messages, mail reminder, test voting process, custom color, quorum, results visualization type, template, url redirect, free-text input/feedback, etc.

### Subscription Management
- [ ]  [**Subscription Plan Selection**](https://github.com/vocdoni/interoperability/issues/229)
    - [ ] Investigate if we can use Stripe for this part and integrate into the backend or if we need to develop certain parts of the subscription management.
    - [ ] Define the database structure for storing the needed plans (max_census_size, specific features and limits)
    - [ ] Develop API for subscription plan selection and management.
    - [ ] Upgrade/Downgrade Subscription
    - [ ] Implement API for subscription changes.
    - [ ] Subscription Renewal and Expiration
    - [ ] Develop API for subscription renewal and expiration management.
