### ISSUE TITLE
EPIC - SaaS Frontend MVP v1

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/interoperability#196]
The SaaS frontend pages and flows should allow to:

### Admin Registration and Authentication
- [x] #197
- [x] #198
- [x] #199
- [x] Email verification page/popup
- [x] #200

### Organization/Team Management
- [x] #201
- [x] #202
- [x] #203
- [x] #204
- [x] #205
- [x] https://github.com/vocdoni/ui-scaffold/issues/844

### Processes Management
- [x] #208
- [x] #210
- [x] #209

### Subscription Management
- [x] #224
- [x] #223
- [x] #225
- [x] Subscription flow with Stripe

### Utils/Misc
- [x] #216
- [ ] #215
- [x] Mailing Service
- [ ] Check subscription expiration date / canceled

### Generals
- [x] #232
- [x] #233
- [x] #217
- [ ] #218

### **V1:**
- [x] #235 
- [x] #226

### Emails 
- [x] #211
- [x] #213
- [ ] #214

**Comment by jpaulet** [comment]
Closing this issue, as we spitted the check/controls in specific issues.
