### ISSUE TITLE
Admin Registration

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/interoperability#197]
As an admin, I want to register with name, email and password so that I can securely log in.

**Tasks:**
- [x] Registration form UI with fields for name, email, password and T&C checkbox acceptance.
- [x] Integration with registration API to handle form submission.
- [x] Email validation UI flow.
- [x] Success and error notifications.
- [x] Popup with Privacy Policy + T&C texts when clicked to the links.

**Acceptance Criteria:**
- [x] Admin can successfully register using email and password.
- [x] Registration triggers an email validation process.
- [x] Appropriate success or error messages are displayed based on the outcome.
- [x] Redirect the admin to the "Create Org" screen.

**Visuals:**
![signup_screen](https://github.com/user-attachments/assets/172c9168-0dd0-4386-9142-fbafa00a44ef)
