### ISSUE TITLE
Password Recovery

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/interoperability#200]
As an admin, I want to recover my password so that I can regain access to my account if I forget my password.

**Tasks:**
- [x] Password recovery form UI to submit email for recovery.
- [x] Password reset form UI to reset password using a token.
- [x] Integration with password recovery and reset APIs.
- [x] Success and error notifications.

**Acceptance Criteria:**
- [ ] Admin can submit their email to receive a password recovery link.
- [ ] Admin can reset their password using the link.
- [ ] Appropriate success or error messages are displayed based on the outcome.

**Visuals:**
![password_screen](https://github.com/user-attachments/assets/c5c655e1-5be3-4b3e-9fe5-a8b0e87dedaa)

**Comment by elboletaire** [comment]
Checked everything on my side as done but I actually cannot try the entire flow unless we enable some kind of e-mail system.
