### ISSUE TITLE
Create Organization

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/interoperability#201]
As an admin, I want to create an organization with specific details so that I can manage my organization's voting processes.

**Tasks:**
- [x] Organization creation form UI to enter organization details.
- [x] Make the mandatory and optional fields very clear and with clear errors messages.
- [x] Integration with organization creation API.
- [x] Success and error notifications.

**Acceptance Criteria:**
- [x] Admin can successfully create an organization by submitting the form.
- [x] Appropriate success or error messages are displayed based on the outcome.

**Visuals**
![New Org](https://github.com/user-attachments/assets/0aebcfc6-1464-4b19-863a-bc5577ea8ec5)
