### ISSUE TITLE
Manage Organization Data

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/interoperability#202]
As an admin, I want to view and update my organization's profile so that all details are current.

**Tasks:**
- [x] Organization profile management UI to display and edit organization details.
- [x] Integration with organization profile API.
- [x] Upload logo and header images.
- [x] Be able to remove the images and upload it again.
- [x] Store the images.
- [x] List possible types:  Assembly, Association, Chamber, Church, City/Municipality, Company, Cooperative, Party, University, Union, Others.
- [x] List countries (Australia, Brazil, Canada, China, France, Germany, India, Italy, Japan, Mexico, Netherlands, New Zealand, Russia, South Africa, South Korea, Spain, Sweden, Switzerland, United Kingdom, United States, Other)
- [x] List timezones
- [x] List size (0-100, 100-250, 250-500, 500-1K, 1K-5K, 5K-10K, +10K)
- [x] Success and error notifications.

**Acceptance Criteria:**
- [x] Admin can view and update organization details.
- [x] Changes are reflected immediately after saving.
- [x] Appropriate success or error messages are displayed based on the outcome.

**Visuals**
![Create New Organization](https://github.com/user-attachments/assets/6b88a02b-b097-4ec8-ac8e-217c1cb9fd59)

**Comment by jpaulet** [comment]
Tested in dev and everything seems to work fine. Closing it.
