### ISSUE TITLE
Team management

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/interoperability#203]
As an admin, I want to be able to view the team members in a list format.

**Tasks:**
- [x] Create the UI page with the team info as a list with each member name / email / role. 
- [x] Button to "Invite Admins" screen
- [x] Information of the nº of admins and the nº of admins allowed in that plan (1/1, 1/3...) 
- [ ] If the nº of admins is already reached, when clicking to "Invite Admins" the "Subscription Modal" must appear.

**Visuals:**
![team_screen](https://github.com/user-attachments/assets/c0fcfcd9-d4c8-489e-a4b3-e37023fbb016)
