### ISSUE TITLE
Admin profile

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/interoperability#204]
As an admin, I want to update my user account details so that my profile is up-to-date.

**Tasks:**
  - [x] Design profile update UI
  - [x] Implement backend API for updating admin profile
  - [x] Create required components and views
  - [x] Test profile update functionality

**Visuals:**
![accountprofile1](https://github.com/user-attachments/assets/7c6a9ae3-4671-444d-87b6-38e9babc2207)
![accountprofile2](https://github.com/user-attachments/assets/b689960a-1a14-4310-8e45-69c26e135bdd)

**Comment by elboletaire** [comment]
WIP https://github.com/vocdoni/ui-scaffold/pull/795
