### ISSUE TITLE
Invite Admins

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/interoperability#205]
As an admin, I want to invite additional admins by email so that they can help manage the organization.

**Tasks:**
- [x] Admin invitation form UI to submit email address (use only 1 email input, not a list of emails).
- [x] Allow to select between the 3 different roles (Admin/Moderator/Guest)
- [x] Integration with the API.
- [x] Trigger the "Invite admin" email.
- [x] After submitting, show a modal explaining the success (Email sent) and allowing to choose between returning to the team page or invite other admin.
- [x] Control the nº of admins allowed based on the organization plan (1/1, 1/3...). If the limit is reached, show the "Subscription Modal" instead of the "Invite admin page".
- [x] Success and error notifications.
- [x] ~~Create the new "Invite Register page", similar than the register page but without the email field and the invite code in the URL. Mark as "validated" once registered.~~ Edit the register page so the e-mail is prefilled and disabled for the user invited to easily signup. Also ensure it's already validated once it's been registered (no need for the verification code flow).

**Acceptance Criteria:**
- [ ] Admin can successfully invite other admins by email.
- [ ] Invitations are sent immediately upon submission.
- [ ] Appropriate success or error messages are displayed based on the outcome.

**Visuals:**
![invite_admins_screen](https://github.com/user-attachments/assets/d3681fb8-e28c-463d-b0b2-f590594db187)

**Comment by elboletaire** [comment]
Can be closed now
