### ISSUE TITLE
[ EPIC ] Metrics

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/interoperability#23]
As Vocdoni, we want to assure our infrastructure health & availability. To do so, we need to run checks on a fixed interval such as every minute to prove a specific endpoint such as /status. 

Also, we want to track certain metrics to have a better understanding of the API/SDK  usage and possible improvements. Create a suite of metrics that can be accessed via a dashboard and with historical data. 

Ideally, we can differentiate between direct API calls & SDK calls (with the SDK version on it). 

**Final outcome of this epic:**
Have a single public dashboard where everyone can check:
- All our nodes' status and historic % uptime.
- All the proposed metrics in real-time and historic data with 1-day granularity.
- Be able to switch between the metric and the historic data as a graph.

Tasks:

**Be able to track the infrastructure usage & status** (SLA): 
- [x] Nodes status and workload: Be able to check all our nodes and status, ideally with a % of uptime and errors.
- [ ] API status: perform fixed checks to know the API status. Add alarms if the API is down.
- [ ] Nº of 40x and 50x errors and % between success/error requests
- [x] Block time generation
- [x] Nº of transactions
- [ ] Nº of tokens purchased (TBD)

**Track usage metrics for the protocol**:
- [ ] Nº Orgs
- [x] Nº processes
- [ ] Nº active processes
- [x] Nº of votes
- [ ] Nº of processes with at least 1 vote
- [x] Nº of used tokens

**Create a minimal dashboard to gather all this information on the same page**
- [x] Create the dashboard
- [x] Add metrics
- [x] Deploy it

**Comment by jpaulet** [comment]
Related to: https://github.com/vocdoni/interoperability/issues/83

**Comment by altergui** [comment]
i marked as :heavy_check_mark: all the items done in MVP #83 
and included 3 of the remaining in #91 

i'm not sure about:
- [ ] API status: perform fixed checks to know the API status. Add alarms if the API is down.

this would need to be implemented outside of vocdoni-node

and this:
- [ ] Nº of 40x and 50x errors and % between success/error requests

for some reason i understood we just wanted to track metrics related to the vochain, no gateway stats. and while i'm happy to implement this idea, it crosses that line, so just wanted confirmation before taking this as well,

**Comment by jpaulet** [comment]
Ok, closing this issue, as the new one tracks the pending issues. About the 40x & 50x it's true that this shouldn't be included in the monitor system itself, but in the gateways or as alerts.
