### ISSUE TITLE
Implement Minimum Viable Security (MVS) in API and SDK

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/interoperability#24]
The plan to implement MVS is:

    SAST - static security review
    SCA - security review of components and libs
    DAST - dynamic security tests

The current status is:

- [ ] SAST - static security review

    - Spectral for static reviewing of API's contracts (OpenAPI standard) 
    - example pipeline: https://github.com/vocdoni/developer-portal/actions/runs/4756872314

 - [ ] SCA - security review of components and libs:
     - we use Trivy successfully in other repos
    - looking for right repo to implement a Pipeline

 - [ ] DAST - dynamic security tests: no started

- [ ] Update API endpoints with extra documentation and introduce metadata information

**Comment by emmdim** [comment]
@chilcano  let's start with the desing of  minimum set of GH CI check for the Rest API provided by https://github.com/vocdoni/vocdoni-node isolated in a concrete branch.

**Comment by emmdim** [comment]
Update. Discussed about possible ways to advance on this in order to be able to merge the code + api specs + testing

We decided that the best way forward is to use a code level (golang) library that would automatically extract the API information from the API implementation.
   * New issue towards this direction: https://github.com/vocdoni/interoperability/issues/62

**Comment by emmdim** [comment]
Next steps:
- https://github.com/vocdoni/interoperability/issues/65

**Comment by emmdim** [comment]
Next steps:
https://github.com/vocdoni/interoperability/issues/70
