### ISSUE TITLE
Deploy the Comercial Network

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/interoperability#52]
As Vocdoni we want a new production-ready network where the high-stake, integrators and paid elections will be run. This production-ready network should have a high availability and low error/failure rate. 

Build/deply the infra necessary to create this network:
- [x] #53
- [ ] #54
- [x] Create an account with tokens
- [ ] #55
- [ ] Configure the alerts system
- [x] Enable the pricing model
- [ ] Testing

Monitoring:
- [ ] Create the new dashboard pointing the new network

SDK
- [ ] Add the new network into the SDK 

Related to discuss:
- https://github.com/vocdoni/interoperability/issues/56

**Comment by jpaulet** [comment]
Next steps & definition: https://hackmd.io/_pHKGTNfQnC4P1xo3FY84g

**Comment by jpaulet** [comment]
@p4u Talk with Roger to start the network deployment.
