### ISSUE TITLE
[ EPIC ] Aragon App off-chain voting plugin v1

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/interoperability#59]
As Vocdoni, we want to implement a off-chain voting plugin for the new Aragon DAOs, where the users can create a process in the Vochain, vote without fees and upload the results in a optimistic mode.

The DAO creator / process creator,  must determine a list of X addresses that will be able to execute the process if the results are correct (like a multisig, N/X) and the valid parameters (threshold, participation, etc.). 

**Backend**:

- [x] Discuss how it will work
- [x] Implement the smart contracts
- [x] Tests
- [x] Deploy it to a test network
- [x] Document

**SDK**:
- [x] TBD: Implement the new SDK methods to support the voting plugin

**Frontend**:
- [x] Start the working group for creating the voting flow
