### ISSUE TITLE
Implement new API to the explorer and disable RPC 

### ISSUE THREAD

**Issue by selankon** [vocdoni/interoperability#61]
Here some tasks that need to be finished before we can disable old RPC from the backend. 

## Pending API implementation

@jordipainan @p4u 

- [x] Transactions on a block https://github.com/vocdoni/interoperability/issues/57
- [x] Transactions paginated list (we can do a Promise.all like with the blocks)

## Pending to merge or be deployed on dev

@jordipainan 

- [x] List of blocks (currently pending merge, this one does a Promise.all of blocks by height https://github.com/vocdoni/explorer-ui/pull/127, it has a blocker) Related: https://github.com/vocdoni/interoperability/issues/33 . Blocked by following PR
- [x] Transaction info -> https://github.com/vocdoni/explorer-ui/pull/119 Blocker -> https://github.com/vocdoni/interoperability/issues/40
- [x] Block details -> https://github.com/vocdoni/explorer-ui/pull/115 Blocker -> https://github.com/vocdoni/interoperability/issues/36
- [x] Organizations list + filters https://github.com/vocdoni/explorer-ui/pull/130 Blocker -> https://github.com/vocdoni/interoperability/issues/63

## Pending explorer implementation 

@selankon 

- [x] Process list + filters https://github.com/vocdoni/explorer-ui/pull/130
- [x] Election list + filters https://github.com/vocdoni/explorer-ui/pull/131
- [x] Replace the useProcessKeys hook (I imagine it's a hook that retrieves the decryption keys of an encrypted election, now they come with the election info)
- [x] Entity metadata  (check where is using `import {  useEntity } from '@vocdoni/react-hooks'`)
- [x] Organization details page https://github.com/vocdoni/explorer-ui/pull/133

## Final changes 

The only remaining PR to merge that will deprecate the RPC is this:

- [x] https://github.com/vocdoni/explorer-ui/pull/138

It already has some pending issues that need to be merged on vocdoni node.

- [x] https://github.com/vocdoni/interoperability/issues/68
- [x] https://github.com/vocdoni/interoperability/issues/57

**Comment by p4u** [comment]
@selankon issue #407 does not exist
