### ISSUE TITLE
Implement Census3 (2nd version)

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/interoperability#64]
Finish the Census3 (2nd version) with the strategies implementation + be able to add new tokens, and integrate it to the SDK & Frontend:

    - Be able to create/review strategies
    - Add strategies to the frontend
    - Be able to vote with strategies
    - Be able to add a new token (submit the address of the contract) via UI: add an address

**Definition**:
- [ ] To define how to mix weights and NFTs

**Backend**:
- [x] #100
- [ ] https://github.com/vocdoni/census3/issues/20
- [x] #44
- [x] #46
- [x] Strategies management and API implementation
- [x] https://github.com/vocdoni/census3/issues/58

**SDK**:
- [x] Implement strategy managing

**Frontend**:
- [ ] Implement census creation from strategy
- [ ] Vote with a strategy

**Documentation**
- [ ]  API documentation
- [x] SDK documentation
- [ ] Frontend documentation
- [ ] Update docs to DevPortal
