### ISSUE TITLE
[ EPIC ] Anonymous Voting

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/interoperability#66]
As Vocdoni, we want to be able to have fully anonymous voting available in the protocol/SDK/UIs to allow the voters to have full privacy. 

**Protocol/Backend**: Implement `Secret Identity Key (SIK)` in the Vochain
- [x] Create the new transactions for SIK: Update and create needed protobuffer definitions (more info [here](https://hackmd.io/8QtTh6FGTn6FlYgiQ1Ubxg?view#Tech-specification)) --> PR [here](https://github.com/vocdoni/dvote-protobuf/pull/63).
- [x] Keeping track of the starting blocks of each open election storing into a no-state database the `startBlock` of every started election. If a election is finished, delete it from the database. If a election is paused, the database will store the current block (height) (more info [here](https://hackmd.io/8QtTh6FGTn6FlYgiQ1Ubxg#SIK-reset)).
- [x] Create new Merkle Tree in the Vochain state ([here](https://github.com/vocdoni/vocdoni-node/blob/main/vochain/state/trees.go#L120)) with similar logic that the `RollingCensus` but using `Poseidon` hash ([current example](https://github.com/vocdoni/vocdoni-node/blob/main/vochain/state/rollingcensus.go))
- [x] Store `SIK` roots for hysteresis into statedb (nostate)
- [ ] Implement the anonymous voting transaction flow with root hysteresis.
- [x] API endpoints and APIClient methods to manage `SIK`'s:
  - [x] Update account metadata setter to handle `SIK` during creation and update the account ([API](https://github.com/vocdoni/vocdoni-node/blob/ed06c3517c0560312eac3ed105f827b00b1efc9f/api/accounts.go#L139) & [APIClient](https://github.com/vocdoni/vocdoni-node/blob/ed06c3517c0560312eac3ed105f827b00b1efc9f/apiclient/account.go#L155))
  - [x] Create API endpoint and APIClient method to delete account `SIK`.
  - [x] Update API endpoints and APIClient methods to retrieve not just the census proof (root + siblings) for an election, but also the `SIK` proof (root + siblings).
- [ ] Review leaf insertion in both trees (`SIK` and census) to ensure that follows something similar to this [example](https://github.com/vocdoni/zk-franchise-proof-circuit/blob/9a2c24e5c0fdddc77f65cac16a9e411dabeb1725/internal/helpers.go#L39).
- [x] Update nullifier formula and implementation to include user `SIK` 
- [x] Deprecate and remove the ZkAddress.
- [x] Update circuit reference and artifacts URL's.
- [ ] Adapt end2end tests.
- [ ] Ensure that any census or sik tree has the default maximum number of levels (`censustree.DefaultMaxLevels`) and uses keys with the default maximum key length (`censustree.DefaultMaxKeyLen = censustree.DefaultMaxLevels / 8`).

**SDK**
- [ ] Bundling
- [ ] Integrate _circom_ into SDK (PoC done! [source code](https://github.com/vocdoni/vocdoni-sdk/tree/poc/anonymous_integration))
- [ ] Implement anonymous voting into the SDK:
  - [ ] Circuit and artifacts management.
  - [ ] Circuit inputs creation and proof generation.
- [ ] Testing

**Frontend**
- [ ] Create the UX/UI
- [ ] Implement into the UI
- [ ] Testing

**Documentation**
- [ ] Create documentation
- [ ] Add to developer portal

**Comment by jpaulet** [comment]
Related: https://github.com/vocdoni/interoperability/issues/14
