### ISSUE TITLE
Election Price

### ISSUE THREAD

**Issue by p4u** [vocdoni/interoperability#67]
From the moment of the merge of this PR https://github.com/vocdoni/vocdoni-node/pull/939 the development network will start computing dynamic prices for new elections, based on a formula.

There is a new endpoint that can be used to estimate the election price before sending the transaction.

On the client side, nothing should be different. The balance will be automatically subtracted from the account's wallet once the transaction is mined.

### election price

Election Price API endpoint for calculating the price of an election.

It takes a JSON object with the 5 election parameters that are required for calculating the price.

**request**
POST /elections/price
```json
{
  "maxCensusSize": 5000,
  "electionBlocks": 158,
  "encryptedVotes": false,
  "anonymousVotes": false,
  "maxVoteOverwrite": 1
}
```

**response** 
(200) `{"price":61}`

### networkCapacity

In `chain/info` response, there is now a new uint64 field `networkCapacity`.

This parameters indicates how many votes per block is the blockchain supposed to achieve. As bigger the capacity as cheaper the elections.

### ToDo

- [ ] Document the new API endpoint
- [ ] Add support for SDK
- [ ] Increase the DEV faucet amount, so the new wallets will have more funds available

**Comment by selankon** [comment]
Could be interesting to document the price formula in a separated doc file under protocol section? @jpaulet

**Comment by p4u** [comment]
New endpoint added with the price factors so the SDK can make its own price predictions.

@marcvelmer @selankon 

```json
curl http://localhost:9090/v2/chain/info/electionPriceFactors -s| jq .                                                                              ✔ 
{
  "basePrice": 5,
  "capacity": 2000,
  "factors": {
    "k1": 0.002,
    "k2": 0.0005,
    "k3": 0.005,
    "k4": 10,
    "k5": 3,
    "k6": 0.0008,
    "k7": 200
  }
}
```

**Comment by selankon** [comment]
Documented here https://github.com/vocdoni/developer-portal/pull/89

**Comment by marcvelmer** [comment]
@p4u Already done in the SDK. Can we close it or there is something still missing?
