### ISSUE TITLE
Voting types abstraction in the SDK/API

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/interoperability#71]
As Vocdoni, we want to be able to have specific methods to create different voting types directly from the SDK. 

Right now, we can create different voting types (single choice, approval, ranked, quadratic) specifying the right parameters in the election creation, but we need a way to be able to discern which voting type is an election, in order to be able to change the way the voters will vote trough the ui-components and also to display the right results. 

**Tasks**:
- [ ] Define the different methods (single choice, multiple choice, approval, ranked, quadratic)
- [ ] Store the voting type in the metadata of the election
- [ ] Implement the new creation methods for each voting type
- [ ] Include vote validity check: https://github.com/vocdoni/vocdoni-sdk/issues/206
- [ ] Test it
- [ ] Document the new methods

When implemented in the SDK/API, we will update/create new UI-components elements to be able to render the options accordingly and the results.

**Comment by jpaulet** [comment]
Closing this generic issue and creating one for each needed voting type.
