### ISSUE TITLE
Explorer: add query filters to some endpoints

### ISSUE THREAD

**Issue by selankon** [vocdoni/interoperability#8]
In addition to implement needed endpoints (see #6 ), the actual Explorer can add query filters to some views, see the following `GET` petitions:

- [x] `chain/organizations/` , filter by organizations id or organizations partial id
- [x] `elections/`.[ In the old implementation](https://docs.vocdoni.io/architecture/services/gateway.html#results-api) this endpoint had the most complex query filter, on the explorer we support:
    - [x] Search by election id or partial id
    - [x] Search by entity id or partial id
    - [x] "Show only processes with results"
    - [x] By status

For transactions and blocks it play only with the pagination.

Now another question is how we are going to implement this filters: as query parameters? On a JSON  object on the request body? My opinion is that this parameters should be added as query parameters, but, to make the API simple, and taking account that this methods will only be used on the Explorer probably, for simplicity maybe we can add it to the request body so the url remains clear. 

Any option is valid for me. 

After implement it, we have to update:

- [ ] SDK
- [x] Developer portal

**Comment by jordipainan** [comment]
Working on it

**Comment by jordipainan** [comment]
Post /chain/organizations/filter

**Comment by selankon** [comment]
@jordipainan I updated the previous answer with the examples

**Comment by jordipainan** [comment]
Ready to merge

**Comment by selankon** [comment]
Hi, I got this error

```
curl -s https://api-dev.vocdoni.net/v2/chain/organizations/filter/page/0 --data '{"organizationId": "0x3d0380f4dcc8aa87be30ef0e38f56dfefeb1cfad"}' | jq .
{
  "error": "cannot parse data as JSON: json: cannot unmarshal object into Go value of type string",
  "code": 4016
}
```

I guess the json is wellformed, may be related to the new error handling? 

Instead `election/filters` works fine:

```
➜ curl -s https://api-dev.vocdoni.net/v2/elections/filter/page/0 --data '{"organizationId": "0x3d0380f4dcc8aa87be30ef0e38f56dfefeb1cfad"}' | jq
```

**Comment by selankon** [comment]
Also, filters  for elections not working

```bash
curl -s https://api-dev.vocdoni.net/v2/elections/filter/page/0 --data '{"organizationId": "0x3d0380f4dcc8aa87be30ef0e38f56dfefeb1cfad"}' | jq # work
curl -s https://api-dev.vocdoni.net/v2/elections/filter/page/0 --data '{"organizationId": "0x3d0380f4dcc8aa87be30e"}' | jq # ERROR: odd length string, should accept partial?

curl -s https://api-dev.vocdoni.net/v2/elections/filter/page/0 --data '{"electionId": "c5d2460186f78da3d27b841edcbbe13ac3f1405336449f4a6af6020000000009"}' | jq # ERROR: org not found
curl -s https://api-dev.vocdoni.net/v2/elections/filter/page/0 --data '{"electionId": "c5d2460186f78da3d27b841edcb"}' | jq # ERROR: odd length

curl -s https://api-dev.vocdoni.net/v2/elections/filter/page/0 --data '{"withResults": true}' | jq # ERROR: org not found
curl -s https://api-dev.vocdoni.net/v2/elections/filter/page/0 --data '{"withResults": false}' | jq # ERROR: org not found

curl -s https://api-dev.vocdoni.net/v2/elections/filter/page/0 --data '{"status": "READY"}' | jq # ERROR: org not found
curl -s https://api-dev.vocdoni.net/v2/elections/filter/page/0 --data '{"status": "ENDED"}' | jq # ERROR: org not found
curl -s https://api-dev.vocdoni.net/v2/elections/filter/page/0 --data '{"status": "CANCELED"}' | jq # ERROR: org not found
curl -s https://api-dev.vocdoni.net/v2/elections/filter/page/0 --data '{"status": "PAUSED"}' | jq # ERROR: org not found
curl -s https://api-dev.vocdoni.net/v2/elections/filter/page/0 --data '{"status": "RESULTS"}' | jq # ERROR: org not found
curl -s https://api-dev.vocdoni.net/v2/elections/filter/page/0 --data '{"status": "PROCESS_UNKNOWN"}' | jq # ERROR: org not found
```

**Comment by jordipainan** [comment]
https://github.com/vocdoni/vocdoni-node/pull/850

**Comment by selankon** [comment]
@jordipainan I tried everything and works really good now :) I just found some minor error that may be addressed:

* You still cannot search by partial organizationId. Is a not planned feature? Also the message is `election not found` if the string is short. Here an example of existing org `0xd1e92e94ce4364ee7be44c6e70960ce9bccd9ba6` 

```bash
curl -s https://api-dev.vocdoni.net/v2/elections/filter/page/0 --data '{"organizationId": "0xd1e92e94ce4364ee"}' | jq         
curl -s https://api-dev.vocdoni.net/v2/chain/organizations/filter/page/0 --data '{"organizationId": "0xd1e92e94ce4364ee7be44c6e709"}' | jq .   
```

* For an empty  filters it return `organization not found`. I guess the only wrong thing here is the error message

```bash
curl -s https://api-stg.vocdoni.net/v2/elections/filter/page/0 --data '{}' | jq
```

* The `withResults` parameter return this error on any case: `one or more parameters are missing`

```
curl -s https://api-dev.vocdoni.net/v2/elections/filter/page/0 --data '{"withResults": true}' | jq
curl -s https://api-dev.vocdoni.net/v2/elections/filter/page/0 --data '{"withResults": false}' | jq 
```

* Not sure if its an error, search by status `PROCESS_UNKNOWN` return any:

```
curl -s https://api-dev.vocdoni.net/v2/elections/filter/page/0 --data '{"status": "PROCESS_UNKNOWN"}' | jq # ERROR: org not found
```

**Comment by jordipainan** [comment]
Hey @selankon

- You can search by any partial organizationID -> `curl -s https://api-dev.vocdoni.net/v2/chain/organizations/filter/page/0 --data '{"organizationId": "0xd1e9"}' | jq .` What you cannot do is to give an invalid Hex data and that is why the JSON parser complies. You can try with any org, it works.

- The message is election not found. Because this is the only available Error message, the organization have 0 elections. Maybe we can change the error message to be more explicit.

- For empty filters -> `curl -s http://localhost:9090/v2/elections/filter/page/0 --data '{}' | jq` I am getting:
```
{
  "error": "one or more parameters are missing",
  "code": 4039
}
```
- For withResults only, I did not allow to pass only this filter, but thinking again it makes sense. Adding asap

- For processunknown I assumed any process status is valid as it is unknown, but it is probably better to count it as another status. Modifying it

**Comment by jordipainan** [comment]
Yup because the first orgId is not a valid hex string (the length is odd) the second one is a valid hex string. I understand this behavior is fine as the api expects a valid hex string.

Thanks to you

**Comment by jordipainan** [comment]
**TODO**

Add:
- [ ] Filter per organization name
- [ ] Filter per process name

**Comment by jpaulet** [comment]
- Counters (add total orgs/elections)
- To discuss in the future: how to curate/list orgs/elections
- To discuss HEX problem

**Comment by selankon** [comment]
Implemented on the sdk:

Org filters: https://github.com/vocdoni/vocdoni-sdk/pull/134
Elections filters: https://github.com/vocdoni/vocdoni-sdk/pull/146

**Comment by jpaulet** [comment]
Waiting for #38
