### ISSUE TITLE
Make wallet signatures messages user-friendly

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/interoperability#82]
Currently in the `ui-scaffold` all the messages that the user needs to sign aren't user-friendly and difficult to understand. To increase user confidence and security while using the app, we should adapt this messages to make them more readable and make sure the user understands what is signing. 

**To-do:**
- [ ] Explore the best way to show this messages to the user. 
- [ ] Detect all the events that triggers a wallet signature.
- [ ] Create a personalized text for each wallet signature that is user-friendly.

**Wallet Signatures & Messages:**

PROPOSAL 1 (to review)

**1 - Create Account:** 
_Welcome to Vocdoni! 
By signing this message, you are creating a new account and accepting the Terms and Conditions (https://vocdoni.io/terms) and Privacy policies (https://vocdoni.io/privacy). 
This request will not trigger a blockchain transaction or cost any gas fees._

**2 - Create Process:**
_This signature request is used to verify you own this wallet address and you accept the Vocdoni Terms and Conditions (https://vocdoni.io/terms). This request will not trigger a blockchain transaction or cost any gas fees.__

**3 - Sign SIK:**
_This signature request is used to create your own secret identity key (SIK) for the Vocdoni protocol and generate your anonymous account. 
Only accept this signature request if you fully trust the application. This request will not trigger a blockchain transaction or cost any gas fees._

**4 - Sign Vote:**
_This signature requests is used to verify you own this wallet address and cast your vote. This request will not trigger a blockchain transaction or cost any gas fees._

**Comment by jpaulet** [comment]
@jpaulet TODO: make the list of each TX and the corresponding text.

**Comment by marcvelmer** [comment]
> 3 - Sign SIK:
> This signature request is used to create your own secret identity key (SIK) for the Vocdoni protocol and generate your anonymous account.
> Only accept this signature request if you fully trust the application. This request will not trigger a blockchain transaction or cost any gas fees.

Done in the SDK v0.3.1.

Rest of the points cannot be done with synchronization with backend @p4u
