### ISSUE TITLE
improve public grafana dashboard

### ISSUE THREAD

**Issue by altergui** [vocdoni/interoperability#91]
after MVP https://github.com/vocdoni/interoperability/issues/83 some issues were left unresolved:

* [ ] when the nodes are starting, the spit out misleading stats. ideally, avoid reporting stats while the node is syncing (or starting up) (cf. https://github.com/vocdoni/interoperability/issues/83#issuecomment-1698888579)
* [ ] "elections by type" is not trivial as the other stats, since there's no code in place to calculate this. I'd need to implement this first in the indexer, adding such a query: https://github.com/vocdoni/vocdoni-node/issues/1114
* [ ] i'd love to also calculate the amount of total tokens (i.e. circulating supply) but is also not trivial, again i'd need to touch the indexer, and i don't even see any code related to tokens until now (only token txs). planned in https://github.com/vocdoni/vocdoni-node/issues/1050

i'd also add a few low hanging fruit i see in https://github.com/vocdoni/interoperability/issues/23 

**Track usage metrics for the protocol**:
- [ ] Nº Orgs
- [ ] Nº active processes
- [ ] Nº of processes with at least 1 vote
